version: '3.8'
services:
  backend_1:
    image: medicina:1
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - target: 8005
        published: 8005
        protocol: tcp
        mode: host
    networks:
      - desarrollo_net
  jennifer_1:
    image: postgres:15.0-bullseye
    environment:
      - TZ=America/Guayaquil
      - POSTGRES_DB=jennifermedicina
      - POSTGRES_PASSWORD=jennyfer18
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_tendencia_data:/var/lib/postgresql/data/pgdata
    networks:
      - desarrollo_net

volumes:
  pg_tendencia_data:
    external: true

networks:
  desarrollo_net:
    external: true
